### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by IsmaelWASH** [ds4owd-001/md-02-assignments-IsmaelWASH#1]
@larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Great job! You can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-02-assignments-IsmaelWASH/commit/12e5693aeb41e021eb0cf1232d6bed8b11fb593f

On each line, one can add comments. A bit like you would do in MS Word with comments and track changes.

I will close the issue for you now.
